Fix legacy iptables symlinks

diff --git a/run b/run
--- a/run
+++ b/run
@@ -70,17 +70,23 @@ firewall_init () {
 
 # Alpine 3.19 changed the default iptables backend to iptables-nft
 # Check that the host supports this and revert to iptables-legacy if needed
+# Can force one or the other using NFTABLES=0/1 env var
 nftables_setup () {
   # Run an iptables command to see if things are working
-  iptables -L &> /dev/null && return
+  [ -z "$NFTABLES" ] && iptables -L &> /dev/null && return
+  [ "$NFTABLES" -eq 1 ] && return
   # If not, change to legacy
-  echo "$(date): Falling back to iptables-legacy"
-  ln -sf /sbin/xtables-legacy-multi /sbin/iptables
-  ln -sf /sbin/xtables-legacy-multi /sbin/iptables-save
-  ln -sf /sbin/xtables-legacy-multi /sbin/iptables-restore
-  ln -sf /sbin/xtables-legacy-multi /sbin/ip6tables
-  ln -sf /sbin/xtables-legacy-multi /sbin/ip6tables-save
-  ln -sf /sbin/xtables-legacy-multi /sbin/ip6tables-restore
+  echo "$(date): Using legacy iptables backend"
+  ln -sf xtables-legacy-multi $(type -p iptables)
+  ln -sf xtables-legacy-multi $(type -p iptables-save)
+  ln -sf xtables-legacy-multi $(type -p iptables-restore)
+  ln -sf xtables-legacy-multi $(type -p ip6tables)
+  ln -sf xtables-legacy-multi $(type -p ip6tables-save)
+  ln -sf xtables-legacy-multi $(type -p ip6tables-restore)
+  if ! iptables -L &> /dev/null; then
+    echo "$(date): Error reverting to legacy iptables backend"
+    fatal_error
+  fi
 }
 
 # Handle shutdown behavior
